# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

stages:
- stage: Base
  displayName: Build base image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Login to the registry
      inputs:
        containerRegistry: 'Docker hub ulrikaugstsson'
        command: 'login'

    - task: Docker@2
      displayName: Build image with esy
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile.base'
        containerRegistry: 'Docker hub ulrikaugstsson'
        repository: 'ulrikaugustsson/esy'
        tags: 'latest'

    - task: Docker@2
      displayName: Push image with esy
      inputs:
        containerRegistry: 'Docker hub ulrikaugstsson'
        repository: 'ulrikaugustsson/esy'
        command: 'push'
        tags: 'latest'

- stage: Build
  displayName: Build image
  dependsOn: [Base]
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      matrix: {
        490: { OCAML_VERSION: '4.9.0' },
        481: { OCAML_VERSION: '4.8.1' }
      }
    steps:
    - task: Docker@2
      displayName: Login to the registry
      inputs:
        containerRegistry: 'Docker hub ulrikaugstsson'
        command: 'login'

    - task: Docker@2
      displayName: Build image with OCaml version $(OCAML_VERSION)
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        containerRegistry: 'Docker hub ulrikaugstsson'
        repository: 'ulrikaugustsson/esy-docker-builder'
        tags: '$(OCAML_VERSION)'
        arguments: --build-arg ocaml_version=$(OCAML_VERSION)

    - task: Docker@2
      displayName: Push image with OCaml version $(OCAML_VERSION)
      inputs:
        containerRegistry: 'Docker hub ulrikaugstsson'
        repository: 'ulrikaugustsson/esy-docker-builder'
        command: 'push'
        tags: '$(OCAML_VERSION)'
